using Riganti.Utils.Infrastructure.Core;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DAL.Entities
{
    /// <summary>
    /// User entity
    /// </summary>
    public class User : IEntity<Guid>
    {
        /// <summary>
        /// Unique id generated by DB
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [Required, StringLength(100)]
        public string Email { get; set; }

        /// <summary>
        /// User name
        /// </summary>
        [Required, StringLength(255)]
        public string Name { get; set; }

        /// <summary>
        /// Password salt
        /// </summary>
        [Required, StringLength(100)]
        public string PasswordSalt { get; set; }

        /// <summary>
        /// Password hash
        /// </summary>
        [Required, StringLength(100)]
        public string PasswordHash { get; set; }

        /// <summary>
        /// Token hash
        /// </summary>
        [Required, StringLength(100)]
        public string TokenHash { get; set; }

        /// <summary>
        /// Date and time when user was created
        /// </summary>
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Date and time when user was last updated
        /// </summary>
        public DateTime? LastUpdatedOn { get; set; }

        /// <summary>
        /// Date and time when user was last logged into system
        /// </summary>
        public DateTime LastLoginOn { get; set; }

        /// <summary>
        /// Collection of user phones
        /// </summary>
        public virtual ICollection<Phone> Telephones { get; set; }
    }
}
